import json
import os
from flask import Blueprint, jsonify

metrics_api = Blueprint("metrics_api", __name__)

_METRICS_PATH = os.path.join(os.path.dirname(__file__), "..", "evaluation", "metrics.json")


@metrics_api.route("/metrics", methods=["GET"])
def get_metrics():
    """
    Returns precomputed model evaluation metrics (accuracy, precision,
    recall, confusion matrix) generated by evaluation/evaluate.py.
    These are real numbers from running the classifier against a
    hand-labeled test set - not invented.
    """
    if not os.path.exists(_METRICS_PATH):
        return jsonify({
            "error": "Metrics not generated yet. Run: python evaluation/evaluate.py"
        }), 404

    with open(_METRICS_PATH) as f:
        data = json.load(f)

    return jsonify(data), 200